

spring:
  profiles:
    active: dev


---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: ${DATABASE_URI:mongodb://root:example@localhost:27017/}
      database: black-hole
      authentication-database: admin
management:
  endpoints:
    web:
      exposure:
        include: '*'

---
spring:
  config:
    activate:
      on-profile: test
  main:
    lazy-initialization: true
  mongodb:
    embedded:
      version: 5.0.5
      